[package]
description="Load and Download LLM Models, Metadata, and Tokenizers"
edition.workspace=true
homepage.workspace=true
license.workspace=true
name="llm_models"
readme="README.md"
repository.workspace=true
version="0.0.1"

[dependencies]
anyhow.workspace=true
byteorder="1.5.0"
colorful.workspace=true
dotenvy.workspace=true
hf-hub={version="0.3.2"}
indenter.workspace=true
llm_prompt.workspace=true
minijinja="2.0.1"
paste="1.0.15"
serde.workspace=true
serde_json.workspace=true
thiserror.workspace=true
tiktoken-rs="0.5.9"
tokenizers="0.20.0"
tracing.workspace=true
