[workspace]
members = [
    "llm_client",
    "llm_devices",
    "llm_interface",
    "llm_models",
    "llm_prompt",
    "llm_utils",
]
resolver = "2"

[workspace.package]
authors = ["Shelby Jenkins"]
edition = "2021"
exclude = ["Cargo.lock", "target/**/*"]
homepage = "https://github.com/shelbyJenkins/llm_client"
license = "MIT"
repository = "https://github.com/shelbyJenkins/llm_client"

[workspace.dependencies]
anyhow = "1.0.90"
colorful = "0.3.2"
dotenvy = "0.15.7"
indenter = "0.3.3"
llm_devices = { path = "./llm_devices", version = "0.1.0" }
llm_interface = { path = "./llm_interface", version = "0.1.0" }
llm_models = { path = "./llm_models", version = "0.1.0" }
llm_prompt = { path = "./llm_prompt", version = "0.1.0" }
llm_utils = { path = "./llm_utils", version = "0.1.0" }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
serial_test = "3.1.1"
thiserror = "1.0.64"
tokio = "1.40.0"
tracing = "0.1.40"
url = "2.5.2"
