[workspace]
members=["llm_client", "llm_client_testing", "llm_interface"]
resolver="2"
[workspace.package]
authors=["Shelby Jenkins"]
edition="2021"
exclude=["Cargo.lock", "target/**/*"]
homepage="https://github.com/shelbyJenkins/llm_client"
license="MIT"
repository="https://github.com/shelbyJenkins/llm_client"
[workspace.dependencies]
anyhow="1.0.89"
llm_utils={path="../llm_utils", version="0.0.9"}
serde="1.0.210"
serde_json="1.0.128"
serial_test="3.1.1"
thiserror="1.0.64"
tokio="1.40.0"
tracing="0.1.40"
url="2.5.2"
