[application]

# App (Project) Name
name="llm_gui"

[web.app]

# HTML title tag content
title="llm_gui"

[web.watcher]
reload_html=true
watch_path=["assets", "public", "src"]

# Additional JavaScript files
script=[]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script=[]
