name: CI

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  RUST_VERSION: 1.83.0
  MACOSX_DEPLOYMENT_TARGET: '12.0'

jobs:
  build:
    name: Build on ${{ matrix.build }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - build: linux-amd64
            os: ubuntu-22.04
          - build: macos-amd64
            os: macos-13
          - build: macos-arm64
            os: macos-14
    env:
      TARGET: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          override: true
          components: clippy, rustfmt

      - name: Cargo fmt
        run: cargo fmt --all -- --check
      - name: Cargo check
        run: cargo check
